# Generated by Django 3.0.6 on 2020-05-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200526_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('ps', models.IntegerField(default=0)),
                ('brand', models.CharField(max_length=64)),
            ],
        ),
    ]
